modLoader="javafml"
loaderVersion="[41,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Limited-Lives/issues"

[[mods]]
    modId="limitedlives"
    version="${file.jarVersion}" #mandatory
    displayName="Limited Lives"
    displayURL="https://ichun.me/mods/limited-lives/"
    authors="iChun"
    description='''
    A tiny mod that limits the number of lives you can have, constantly draining your health, before banning you from the server.
    '''

[[dependencies.limitedlives]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.limitedlives]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
